Attribute VB_Name = "Einstellungen_laden"
Option Explicit
Private Declare Function GetPrivateProfileString Lib "kernel32" Alias "GetPrivateProfileStringA" (ByVal lpApplicationName As String, ByVal lpKeyName As Any, ByVal lpDefault As String, ByVal lpReturnedString As String, ByVal nSize As Long, ByVal lpFileName As String) As Long
Public Sub laden()
    Dim i As Integer
    
    frmMain.Ziel.Text = iniladen("Grund-Einstellungen", "Ziel")
    frmMain.Quelle.Text = iniladen("Grund-Einstellungen", "Quelle")
    frmMain.work.Text = iniladen("Grund-Einstellungen", "Arbeit")
    MP3cbrparameter = iniladen("MP3-CBR-Einstellungen", "Lamestring")
    MP3cbrmenu.cbrbitrate.ListIndex = iniladen("MP3-CBR-Einstellungen", "Bitrate")
    MP3cbrmenu.Slider1.CurPosition = iniladen("MP3-CBR-Einstellungen", "Qualität")
    MP3cbrmenu.stereomode.ListIndex = iniladen("MP3-CBR-Einstellungen", "Stereomode")
    MP3vbrparameter = iniladen("MP3-VBR-Einstellungen", "Lamestring")
    MP3vbrmenu.neu.value = iniladen("MP3-VBR-Einstellungen", "Neue Methode")
    MP3vbrmenu.alt.value = iniladen("MP3-VBR-Einstellungen", "Alte Methode")
    MP3vbrmenu.maxbit.ListIndex = iniladen("MP3-VBR-Einstellungen", "Maximale Bitrate")
    MP3vbrmenu.minbit.ListIndex = iniladen("MP3-VBR-Einstellungen", "Minimale Bitrate")
    MP3vbrmenu.stereomode.ListIndex = iniladen("MP3-VBR-Einstellungen", "Stereomode")
    MP3vbrmenu.Slider1.CurPosition = iniladen("MP3-VBR-Einstellungen", "Qualität")
    MP3abrparameter = iniladen("MP3-ABR-Einstellungen", "Lamestring")
    MP3abrmenu.abrbitrate.ListIndex = iniladen("MP3-ABR-Einstellungen", "Bitrate")
    MP3abrmenu.stereomode.ListIndex = iniladen("MP3-ABR-Einstellungen", "Stereomode")
    MP3abrmenu.Slider1.CurPosition = iniladen("MP3-ABR-Einstellungen", "Qualität")
    MP2cbrmenu.cbrbitrate.Text = iniladen("MP2-CBR-Einstellungen", "Bitrate")
    MP2cbrmenu.stereomode.Text = iniladen("MP2-CBR-Einstellungen", "Stereomode")
    MP2cbrparameter = iniladen("MP2-CBR-Einstellungen", "Parameter")
    MP2vbrmenu.cbrbitrate.Text = iniladen("MP2-VBR-Einstellungen", "Bitrate")
    MP2vbrmenu.stereomode.Text = iniladen("MP2-VBR-Einstellungen", "Stereomode")
    MP2vbrparameter = iniladen("MP2-VBR-Einstellungen", "Parameter")
    MP2vbrmenu.Slider1.CurPosition = iniladen("MP2-VBR-Einstellungen", "Bitrate / Bevorzugung")
    oggmenu.maxaktiv.value = iniladen("OGG-Einstellungen", "Max aktiv")
    oggmenu.minaktiv.value = iniladen("OGG-Einstellungen", "Min aktiv")
    oggmenu.abraktiv.value = iniladen("OGG-Einstellungen", "ABR aktiv")
    oggmenu.maxbit.Text = iniladen("OGG-Einstellungen", "Maximale Bitrate")
    oggmenu.minbit.Text = iniladen("OGG-Einstellungen", "Minimale Bitrate")
    oggmenu.abrbit.Text = iniladen("OGG-Einstellungen", "Mittlere Bitrate")
    oggmenu.managementengine.value = iniladen("OGG-Einstellungen", "Management Engine")
    oggmenu.normalengine.value = iniladen("OGG-Einstellungen", "Normale Engine")
    oggmenu.Slider1.CurPosition = iniladen("OGG-Einstellungen", "Qualität")
    OGGparameter = iniladen("OGG-Einstellungen", "Parameter")
    Aktivierauswahl.mp3normal_aktiv.value = iniladen("Aktivierungs-Einstellungen", "MP3-Normalize")
    Aktivierauswahl.mp3gain_aktiv.value = iniladen("Aktivierungs-Einstellungen", "MP3-Gain")
    Aktivierauswahl.scan_aktiv.value = iniladen("Aktivierungs-Einstellungen", "Scannen")
    Aktivierauswahl.sort_aktiv.value = iniladen("Aktivierungs-Einstellungen", "Sortierung")
    Aktivierauswahl.mp3_cbr_aktiv.value = iniladen("Aktivierungs-Einstellungen", "MP3-CBR")
    Aktivierauswahl.mp3_vbr_aktiv.value = iniladen("Aktivierungs-Einstellungen", "MP3-VBR")
    Aktivierauswahl.mp3_abr_aktiv.value = iniladen("Aktivierungs-Einstellungen", "MP3-ABR")
    Aktivierauswahl.mp2_cbr_aktiv.value = iniladen("Aktivierungs-Einstellungen", "MP2-CBR")
    Aktivierauswahl.mp2_vbr_aktiv.value = iniladen("Aktivierungs-Einstellungen", "MP2-VBR")
    Aktivierauswahl.timec.value = iniladen("Aktivierungs-Einstellungen", "Zeitsteuerung")
    Aktivierauswahl.oggnormal_aktiv.value = iniladen("Aktivierungs-Einstellungen", "OGG-Normalize")
    Aktivierauswahl.plloggeraktiv.value = iniladen("Aktivierungs-Einstellungen", "Playlist Logger")
    allgemeine.quelldel.value = iniladen("Allgemeine-Einstellungen", "Quelldateien löschen")
    allgemeine.sprache = iniladen("Allgemeine-Einstellungen", "Sprache")
    allgemeine.cpuaktiv.value = iniladen("Allgemeine-Einstellungen", "CPU Meter")
    allgemeine.Prio_mce.ListIndex = iniladen("Allgemeine-Einstellungen", "MCE-Manager Priority")
    allgemeine.prio_shell.ListIndex = iniladen("Allgemeine-Einstellungen", "Shell Priority")
    allgemeine.autostart.value = iniladen("Allgemeine-Einstellungen", "Minimized")
    allgemeine.ueberschreiben.value = iniladen("Allgemeine-Einstellungen", "Vorhandene Song ersetzten")
    allgemeine.bevorzugen.value = iniladen("Allgemeine-Einstellungen", "Unzensiert")
    allgemeine.showdos.value = iniladen("Allgemeine-Einstellungen", "Dos Tools")
    allgemeine.mp2test.value = iniladen("Allgemeine-Einstellungen", "MP2 Test")
    allgemeine.timesync_konv.value = iniladen("Allgemeine-Einstellungen", "Zeitsync vor Prozess")
    allgemeine.coverdownload.value = iniladen("Allgemeine-Einstellungen", "Coverdownload")
    allgemeine.spshow.value = iniladen("Allgemeine-Einstellungen", "Splashscreen")
    mp3gain.constant.value = iniladen("MP3-Gain-Einstellungen", "Konstante Verstärkung")
    mp3gain.auto.value = iniladen("MP3-Gain-Einstellungen", "Automatische Verstärkung")
    mp3gain.Slider1.CurPosition = iniladen("MP3-Gain-Einstellungen", "Wert der Verstärkung")
    mp3gainstring = iniladen("MP3-Gain-Einstellungen", "Mp3gain-string")
    normal.prozenable = iniladen("Normalize-Einstellungen", "Prozentuelle Verstärkung")
    normal.peakprozslider.CurPosition = iniladen("Normalize-Einstellungen", "Prozentuellewert")
    normal.dbenable.value = iniladen("Normalize-Einstellungen", "Konstante Verstärkung")
    normal.peakdbslider.CurPosition = iniladen("Normalize-Einstellungen", "DB-Wert")
    normal.bufferslider.CurPosition = iniladen("Normalize-Einstellungen", "Buffer")
    normoptions = iniladen("Normalize-Einstellungen", "Parameter")
    Scannen.sec_wahl.value = iniladen("Scannen-Einstellungen", "Sekunden")
    Scannen.min_wahl.value = iniladen("Scannen-Einstellungen", "Minuten")
    Scannen.hour_wahl.value = iniladen("Scannen-Einstellungen", "Stunden")
    Scannen.day_wahl.value = iniladen("Scannen-Einstellungen", "Tage")
    Scannen.Slider_takt.CurPosition = iniladen("Scannen-Einstellungen", "Wert")
    Scannen.minfiles.CurPosition = iniladen("Scannen-Einstellungen", "File Grenzwert")
    sort.v1.ListIndex = iniladen("Sortierung-Einstellungen", "Verzeichnis1")
    sort.V2.ListIndex = iniladen("Sortierung-Einstellungen", "Verzeichnis2")
    sort.V3.ListIndex = iniladen("Sortierung-Einstellungen", "Verzeichnis3")
    sort.V4.ListIndex = iniladen("Sortierung-Einstellungen", "Verzeichnis4")
    sort.komma.value = iniladen("Sortierung-Einstellungen", "Nach Komma abschneiden")
    sort.artikel.value = iniladen("Sortierung-Einstellungen", "Artikel abschneiden")
    tagging.drift.CurPosition = iniladen("Tagging-Einstellungen", "Driftrate")
    tagging.delsize(0).CurPosition = iniladen("Tagging-Einstellungen", "MP2 unterhalb löschen")
    tagging.korrsymbol.ListIndex = iniladen("Tagging-Einstellungen", "Korrektursymbol")
    tagging.zeitauswahl.ListIndex = iniladen("Tagging-Einstellungen", "Zeitauswahl")
    tagging.dauerslider(1).CurPosition = iniladen("Tagging-Einstellungen", "MP2 Längenabweichung")
    allgemeine.textdownload.value = iniladen("Tagging-Einstellungen", "Songtext download")
    Zeitsteuerung.starth.ListIndex = iniladen("Zeitsteuerung-Einstellungen", "Startzeit Stunde")
    Zeitsteuerung.startm.ListIndex = iniladen("Zeitsteuerung-Einstellungen", "Startzeit Minute")
    Zeitsteuerung.endh.ListIndex = iniladen("Zeitsteuerung-Einstellungen", "Endzeit Stunde")
    Zeitsteuerung.endm.ListIndex = iniladen("Zeitsteuerung-Einstellungen", "Endzeit Minute")
    Zeitsteuerung.montag.value = iniladen("Zeitsteuerung-Einstellungen", "Montag")
    Zeitsteuerung.Dienstag.value = iniladen("Zeitsteuerung-Einstellungen", "Dienstag")
    Zeitsteuerung.Mittwoch.value = iniladen("Zeitsteuerung-Einstellungen", "Mittwoch")
    Zeitsteuerung.Donnerstag.value = iniladen("Zeitsteuerung-Einstellungen", "Donnerstag")
    Zeitsteuerung.Freitag.value = iniladen("Zeitsteuerung-Einstellungen", "Freitag")
    Zeitsteuerung.Samstag.value = iniladen("Zeitsteuerung-Einstellungen", "Samstag")
    Zeitsteuerung.Sonntag.value = iniladen("Zeitsteuerung-Einstellungen", "Sonntag")
    frmMain.senderauswahl.ListIndex = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", "Aufnahme")
    d2set.Port.Text = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", "Port")
    d2set.IP.Text = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", "IP")
    d2set.pw.Text = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", "Passwort")
    d2set.Text45.Text = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", "Benutzername")
    d2set.db2.value = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", "D-Box")
    d2set.dreamb.value = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", "Dreambox / Enigma")
    frmMain.mp3extension.value = iniladen("Grund-Einstellungen", "mp3")
    frmMain.mp2extension.value = iniladen("Grund-Einstellungen", "mp2")
    frmMain.oggextension.value = iniladen("Grund-Einstellungen", "ogg")
    frmMain.noextension.value = iniladen("Grund-Einstellungen", "Keine Konvertierung")
    Aktivierauswahl.mp2normal_aktiv.value = iniladen("Aktivierungs-Einstellungen", "MP2-Normalize")
    allgemeine.igext.value = iniladen("Allgemeine-Einstellungen", "Ignoriere Format")
    
    For i = 0 To 20
        d2set.SenderID(i).Text = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", Str$(i) + ".EPG-Name")
        Genre.genreID(i).Text = iniladen("Genre-Einstellungen", "Genre" + Str$(i))
        d2set.APidID(i).Text = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", Str$(i) + ".APid")
        plbezeichnung.plID(i).Text = iniladen("Playlist", Str$(i) + ".Playlistname")
        d2set.T1(i).value = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", Str$(i) + ".Multi-channel 1")
        d2set.T2(i).value = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", Str$(i) + ".Multi-channel 2")
        d2set.T3(i).value = iniladen("Neutrino, Dreambox, Enigma, Kanal-Umsetzung", Str$(i) + ".Multi-channel 3")
        Genre.genrepl(i) = plbezeichnung.plID(i).Text
        d2set.d2setPL(i).Caption = plbezeichnung.plID(i).Text
        manpl.ManDLPL(i).Caption = plbezeichnung.plID(i).Text
        PlaylistLoggerSettings.loggerpl(i).Caption = plbezeichnung.plID(i).Text
        PL_Verwendung.auswahlpl(i).Caption = plbezeichnung.plID(i).Text
        PlaylistLoggerSettings.kennung(i).Text = iniladen("Playlist", Str$(i) + ".Kennung")
        PL_Verwendung.uselogged(i).value = iniladen("Playlist", Str$(i) + ".Verwendung Logged")
        PL_Verwendung.useonline(i).value = iniladen("Playlist", Str$(i) + ".Verwendung Online")
        OnAir.onairsender.AddItem plbezeichnung.plID(i).Text
    Next i
    
    OnAir.onairsender.ListIndex = iniladen("On Air", "Auswahl")
    Set db = OpenDatabase(App.Path + "\Datenbank\Musik-Datenbank.mdb") 'Öffnet Datenbank
    Set RS = db.OpenRecordset("select * from tracks") 'Tabelle auswählen
    DBdurchsuchen.Auswahl.ListIndex = iniladen("Datenbank", "Sortierung")
    RS.Close
    Set RS = Nothing
    Set db = Nothing
    frmMain.Hide
End Sub
Private Function iniladen(Menu1 As String, Menu2 As String) As String
    Dim buffer As String, wertlen As Integer
    
    frmMain.Hide
    buffer = Space$(255)
    wertlen = GetPrivateProfileString(Menu1, Menu2, vbNullString, buffer, Len(buffer), App.Path + "\settings.ini")
    iniladen = Mid$(buffer, 1, wertlen)
End Function
