Attribute VB_Name = "Sprache"
Option Explicit
Private Declare Function GetPrivateProfileString Lib "kernel32" Alias "GetPrivateProfileStringA" (ByVal lpApplicationName As String, ByVal lpKeyName As Any, ByVal lpDefault As String, ByVal lpReturnedString As String, ByVal nSize As Long, ByVal lpFileName As String) As Long
Public Sub sprach()
    MP3abrmenu.Caption = iniladen(1)
    MP3abrmenu.Label3.Caption = iniladen(2) + ":"
    oggmenu.abraktiv.Caption = MP3abrmenu.Label3.Caption
    MP3abrmenu.Label4.Caption = iniladen(3)
    MP2cbrmenu.Label2.Caption = MP3abrmenu.Label4.Caption + ":"
    MP2vbrmenu.Label2.Caption = MP3abrmenu.Label4.Caption + ":"
    MP3cbrmenu.Label2.Caption = MP3abrmenu.Label4.Caption
    MP3vbrmenu.Label4.Caption = MP3abrmenu.Label4.Caption
    MP3abrmenu.Label2.Caption = iniladen(4)
    MP3cbrmenu.Label7.Caption = MP3abrmenu.Label2.Caption
    MP3vbrmenu.Label5.Caption = MP3abrmenu.Label2.Caption
    MP3abrmenu.Label5.Caption = iniladen(5)
    MP3cbrmenu.Label9.Caption = MP3abrmenu.Label5.Caption
    MP3vbrmenu.Label6.Caption = MP3abrmenu.Label5.Caption
    MP2vbrmenu.Label9.Caption = MP3abrmenu.Label5.Caption
    oggmenu.Label6.Caption = MP3abrmenu.Label5.Caption
    MP3abrmenu.Label6.Caption = iniladen(6)
    MP3cbrmenu.Label10.Caption = MP3abrmenu.Label6.Caption
    MP3vbrmenu.Label7.Caption = MP3abrmenu.Label6.Caption
    MP2vbrmenu.Label10.Caption = MP3abrmenu.Label6.Caption
    oggmenu.Label7.Caption = MP3abrmenu.Label6.Caption
    frmMain.Label100.Caption = iniladen(7) + ":"
    Aktivierauswahl.OK.Caption = iniladen(8)
    allgemeine.OK.Caption = Aktivierauswahl.OK.Caption
    d2set.OK.Caption = Aktivierauswahl.OK.Caption
    Database.OK.Caption = Aktivierauswahl.OK.Caption
    DBdurchsuchen.OK.Caption = Aktivierauswahl.OK.Caption
    Genre.OK.Caption = Aktivierauswahl.OK.Caption
    manpl.OK.Caption = Aktivierauswahl.OK.Caption
    MP2cbrmenu.lameok.Caption = Aktivierauswahl.OK.Caption
    MP2vbrmenu.lameok.Caption = Aktivierauswahl.OK.Caption
    MP3abrmenu.OK.Caption = Aktivierauswahl.OK.Caption
    MP3cbrmenu.lameok.Caption = Aktivierauswahl.OK.Caption
    mp3gain.OK.Caption = Aktivierauswahl.OK.Caption
    MP3vbrmenu.OK.Caption = Aktivierauswahl.OK.Caption
    normal.OK.Caption = Aktivierauswahl.OK.Caption
    oggmenu.OK.Caption = Aktivierauswahl.OK.Caption
    OnAir.OK.Caption = Aktivierauswahl.OK.Caption
    Pfadsuchen.command1.Caption = Aktivierauswahl.OK.Caption
    PL_Verwendung.OK.Caption = Aktivierauswahl.OK.Caption
    PlaylistLoggerSettings.OK.Caption = Aktivierauswahl.OK.Caption
    plbezeichnung.OK.Caption = Aktivierauswahl.OK.Caption
    Scannen.OK.Caption = Aktivierauswahl.OK.Caption
    sort.OK.Caption = Aktivierauswahl.OK.Caption
    Statistik.OK.Caption = Aktivierauswahl.OK.Caption
    tagging.OK.Caption = Aktivierauswahl.OK.Caption
    Timesyncron.OK.Caption = Aktivierauswahl.OK.Caption
    Zeitsteuerung.OK.Caption = Aktivierauswahl.OK.Caption
    Aktivierauswahl.Caption = iniladen(9)
    frmMain.normalisierung_menu.Caption = iniladen(10)
    frmMain.Label15.Caption = frmMain.normalisierung_menu.Caption + ":"
    frmMain.scan_menu.Caption = iniladen(11)
    Aktivierauswahl.Label11.Caption = frmMain.scan_menu.Caption + ":"
    Scannen.Caption = frmMain.scan_menu.Caption
    frmMain.Label22.Caption = frmMain.scan_menu.Caption + ":"
    Aktivierauswahl.scan_aktiv.Caption = iniladen(12)
    frmMain.sortierung_menu.Caption = iniladen(13)
    Aktivierauswahl.Label12.Caption = frmMain.sortierung_menu.Caption + ":"
    sort.Caption = frmMain.sortierung_menu.Caption
    frmMain.Label14.Caption = frmMain.sortierung_menu.Caption + ":"
    Aktivierauswahl.sort_aktiv.Caption = iniladen(14)
    frmMain.Konvertierung_menu.Caption = iniladen(15)
    Aktivierauswahl.Label13.Caption = frmMain.Konvertierung_menu.Caption + ":"
    Aktivierauswahl.mp3_cbr_aktiv.Caption = iniladen(16)
    frmMain.cbr_menu.Caption = Aktivierauswahl.mp3_cbr_aktiv.Caption
    Aktivierauswahl.mp2_cbr_aktiv.Caption = Aktivierauswahl.mp3_cbr_aktiv.Caption
    MP3cbrmenu.Label3.Caption = Aktivierauswahl.mp3_cbr_aktiv.Caption + ":"
    frmMain.mp2cbr_mnu.Caption = Aktivierauswahl.mp3_cbr_aktiv.Caption
    Aktivierauswahl.mp3_vbr_aktiv.Caption = iniladen(17)
    frmMain.vbr_menu.Caption = Aktivierauswahl.mp3_vbr_aktiv.Caption
    frmMain.mp2vbr_mnu.Caption = Aktivierauswahl.mp3_vbr_aktiv.Caption
    Aktivierauswahl.mp2_vbr_aktiv.Caption = Aktivierauswahl.mp3_vbr_aktiv.Caption
    Aktivierauswahl.mp3_abr_aktiv.Caption = iniladen(18)
    frmMain.abr_menu.Caption = Aktivierauswahl.mp3_abr_aktiv.Caption
    frmMain.Label2(1).Caption = iniladen(19) + ":"
    OnAir.Label5(0).Caption = frmMain.Label2(1).Caption
    frmMain.genre_menu.Caption = iniladen(20)
    frmMain.plbez.Caption = iniladen(21)
    frmMain.usepl_mnu.Caption = iniladen(22)
    frmMain.pllogger_mnu.Caption = iniladen(23)
    Aktivierauswahl.Label2.Caption = iniladen(24)
    frmMain.mnu_mp2convert.Caption = Aktivierauswahl.Label2.Caption
    Aktivierauswahl.Label2.Caption = Aktivierauswahl.Label2.Caption + ":"
    allgemeine.Caption = iniladen(25)
    allgemeine.quelldel.Caption = iniladen(26)
    frmMain.Label30.Caption = iniladen(27) + ":"
    allgemeine.Label7.Caption = iniladen(28) + ":"
    MP3cbrmenu.Caption = iniladen(29)
    Aktivierauswahl.plloggeraktiv.Caption = iniladen(30)
    mp3gain.Caption = iniladen(31) + ":"
    mp3gain.auto.Caption = iniladen(32)
    mp3gain.constant.Caption = iniladen(33)
    frmMain.ogg_menu.Caption = iniladen(34)
    Aktivierauswahl.Label100.Caption = frmMain.ogg_menu.Caption + ":"
    normal.Caption = iniladen(35) + ":"
    normal.prozenable.Caption = iniladen(36)
    normal.dbenable.Caption = iniladen(37)
    normal.Label4.Caption = iniladen(38) + ":"
    frmMain.mnu_db.Caption = iniladen(39)
    frmMain.Statisik.Caption = iniladen(40)
    Pfadsuchen.Abbrechen.Caption = iniladen(41)
    frmMain.Abbrechen.Caption = Pfadsuchen.Abbrechen.Caption
    Scannen.Label2.Caption = iniladen(42) + ":"
    Scannen.sec_wahl.Caption = iniladen(43)
    Scannen.min_wahl.Caption = iniladen(44)
    Zeitsteuerung.Label6.Caption = Scannen.min_wahl.Caption + ":"
    Zeitsteuerung.Label4.Caption = Scannen.min_wahl.Caption + ":"
    Scannen.hour_wahl.Caption = iniladen(45)
    Zeitsteuerung.Label5.Caption = Scannen.hour_wahl.Caption + ":"
    Zeitsteuerung.Label3.Caption = Scannen.hour_wahl.Caption + ":"
    Scannen.day_wahl.Caption = iniladen(46)
    sort.Label2.Caption = "1. " + iniladen(47) + ":"
    sort.Label3.Caption = "2. " + iniladen(47) + ":"
    sort.Label4.Caption = "3. " + iniladen(47) + ":"
    sort.Label5.Caption = "4. " + iniladen(47) + ":"
    sort.komma.Caption = iniladen(48)
    tagging.Caption = iniladen(49)
    tagging.Label3.Caption = iniladen(50) + ":"
    tagging.Label6.Caption = iniladen(51) + ":"
    tagging.Label5.Caption = iniladen(52) + ":"
    MP3vbrmenu.Caption = iniladen(53)
    MP3vbrmenu.neu.Caption = iniladen(54)
    MP3vbrmenu.alt.Caption = iniladen(55)
    MP3vbrmenu.Label2.Caption = iniladen(56) + ":"
    oggmenu.maxaktiv.Caption = MP3vbrmenu.Label2.Caption
    MP3vbrmenu.Label3.Caption = iniladen(57) + ":"
    oggmenu.minaktiv.Caption = MP3vbrmenu.Label3.Caption
    Zeitsteuerung.Label1.Caption = iniladen(58) + ":"
    tagging.Label10.Caption = iniladen(59) + ":"
    d2set.Label7.Caption = iniladen(60) + ":"
    frmMain.aufnahmestart.Caption = iniladen(61)
    frmMain.aufnahmestop.Caption = iniladen(62)
    frmMain.Label5.Caption = iniladen(63) + ":"
    frmMain.Label25.Caption = frmMain.Label5.Caption
    frmMain.Label1.Caption = iniladen(64) + ":"
    frmMain.dadab.Caption = iniladen(65)
    frmMain.qsuchen.Caption = iniladen(66)
    frmMain.zsuchen.Caption = frmMain.qsuchen.Caption
    frmMain.Label4.Caption = iniladen(67) + ":"
    frmMain.Label24.Caption = iniladen(68) + ":"
    frmMain.noextension.Caption = iniladen(69)
    frmMain.Label3.Caption = iniladen(70) + ":"
    frmMain.Label13.Caption = iniladen(71) + ":"
    frmMain.Label12.Caption = iniladen(72) + ":"
    frmMain.start.Caption = iniladen(73)
    frmMain.untaggedtaggen.Caption = iniladen(74)
    frmMain.Nachsortierung.Caption = iniladen(75)
    Zeitsteuerung.Label2.Caption = iniladen(76) + ":"
    frmMain.command1.Caption = iniladen(77)
    frmMain.mnu_dbsuche.Caption = iniladen(78)
    frmMain.minim.Caption = iniladen(79)
    frmMain.save_menu.Caption = iniladen(80)
    frmMain.setting_menu.Caption = iniladen(82)
    frmMain.aktivir_menu.Caption = iniladen(83)
    frmMain.allgemein_menu.Caption = iniladen(84)
    PL_Verwendung.Label5(1) = iniladen(85) + ":"
    PL_Verwendung.Label5(2) = iniladen(86) + ":"
    PlaylistLoggerSettings.Label5(1) = iniladen(87) + ":"
    frmMain.tagging_menu.Caption = iniladen(88)
    frmMain.editdb.Caption = iniladen(89)
    frmMain.kontakt_menu.Caption = iniladen(90)
    aktlng = iniladen(91)
    deaktlng = iniladen(92)
    frmMain.mnu_convert.Caption = iniladen(93)
    tagging.Label12.Caption = iniladen(94) + ":"
    frmMain.d2settings.Caption = iniladen(95)
    d2set.Caption = frmMain.d2settings.Caption
    d2set.Label2.Caption = iniladen(96) + ":"
    d2set.Label3.Caption = iniladen(97) + ":"
    frmMain.pldl.Caption = iniladen(98)
    frmMain.aufnahmestart.Caption = iniladen(99)
    frmMain.aufnahmestop.Caption = iniladen(100)
    frmMain.plsettings_mnu.Caption = iniladen(101)
    Genre.Label3.Caption = iniladen(102)
    d2set.Label5.Caption = Genre.Label3.Caption + ":"
    allgemeine.autostart.Caption = iniladen(103)
    d2set.Label6.Caption = iniladen(104) + ":"
    Timesyncron.Caption = iniladen(106)
    frmMain.timesync.Caption = Timesyncron.Caption
    Timesyncron.Label4.Caption = iniladen(107)
    Timesyncron.Label5.Caption = iniladen(108)
    Timesyncron.command1.Caption = iniladen(109)
    allgemeine.cpuaktiv.Caption = iniladen(110)
    sort.artikel.Caption = iniladen(111)
    Zeitsteuerung.montag.Caption = iniladen(112)
    Zeitsteuerung.Dienstag.Caption = iniladen(113)
    Zeitsteuerung.Mittwoch.Caption = iniladen(114)
    Zeitsteuerung.Donnerstag.Caption = iniladen(115)
    Zeitsteuerung.Freitag.Caption = iniladen(116)
    Zeitsteuerung.Samstag.Caption = iniladen(117)
    Zeitsteuerung.Sonntag.Caption = iniladen(118)
    frmMain.Label27.Caption = iniladen(119) + ":"
    OnAir.Label5(1).Caption = frmMain.Label27.Caption
    DBdurchsuchen.Label3(0) = frmMain.Label27.Caption
    frmMain.timecontrol.Caption = iniladen(120)
    Zeitsteuerung.Caption = frmMain.timecontrol.Caption
    Aktivierauswahl.Label4.Caption = frmMain.timecontrol.Caption + ":"
    frmMain.Label6.Caption = frmMain.timecontrol.Caption + ":"
    Aktivierauswahl.timec.Caption = iniladen(121)
    Genre.Label2.Caption = iniladen(122)
    allgemeine.textdownload.Caption = iniladen(123)
    allgemeine.Label2.Caption = iniladen(124) + ":"
    allgemeine.Label3.Caption = iniladen(125) + ":"
    Genre.Caption = iniladen(126)
    allgemeine.ueberschreiben.Caption = iniladen(127)
    frmMain.Label31.Caption = iniladen(128) + ":"
    OnAir.Label5(2).Caption = frmMain.Label31.Caption
    DBdurchsuchen.Label3(1) = frmMain.Label31.Caption
    frmMain.Label32.Caption = iniladen(129) + ":"
    OnAir.Label5(3).Caption = frmMain.Label32.Caption
    DBdurchsuchen.Label3(2) = frmMain.Label32.Caption
    frmMain.Label33.Caption = iniladen(130) + ":"
    DBdurchsuchen.Label3(5) = frmMain.Label33.Caption
    frmMain.Label34.Caption = iniladen(131) + ":"
    OnAir.Label5(5).Caption = frmMain.Label34.Caption
    DBdurchsuchen.Label3(3) = frmMain.Label34.Caption
    frmMain.Label38(3).Caption = iniladen(132) + ":"
    OnAir.Label5(4).Caption = frmMain.Label38(3).Caption
    frmMain.Label21.Caption = iniladen(133) + ":"
    Database.Label1(0).Caption = frmMain.Label21.Caption
    frmMain.Label36(0).Caption = iniladen(134) + ":"
    frmMain.Label36(1).Caption = iniladen(135) + ":"
    frmMain.Label37.Caption = iniladen(136) + ":"
    frmMain.Label50.Caption = iniladen(137) + ":"
    frmMain.Label52(0).Caption = iniladen(138) + ":"
    frmMain.Label35.Caption = iniladen(139) + ":"
    frmMain.Label38(7).Caption = iniladen(140) + ":"
    frmMain.Label38(0).Caption = iniladen(141) + ":"
    frmMain.Label38(2).Caption = iniladen(142) + ":"
    PL_Verwendung.Label5(0).Caption = frmMain.Label38(2).Caption
    PlaylistLoggerSettings.Label5(0) = frmMain.Label38(2).Caption
    frmMain.plloggerlabel.Caption = iniladen(143) + ":"
    Aktivierauswahl.PLlogger(1).Caption = frmMain.plloggerlabel.Caption
    frmMain.plloggerdaten.Caption = iniladen(144) + ":"
    frmMain.Label7.Caption = iniladen(145) + ":"
    allgemeine.bevorzugen.Caption = iniladen(146)
    allgemeine.showdos.Caption = iniladen(147)
    allgemeine.mp2test.Caption = iniladen(148)
    allgemeine.textdownload.Caption = iniladen(149)
    allgemeine.coverdownload.Caption = iniladen(150)
    allgemeine.timesync_konv.Caption = iniladen(151)
    MP2cbrmenu.Label3.Caption = iniladen(152) + ":"
    MP2vbrmenu.Label3.Caption = MP2cbrmenu.Label3.Caption
    DBdurchsuchen.Label3(11).Caption = MP2cbrmenu.Label3.Caption
    MP2vbrmenu.Label7.Caption = iniladen(153) + ":"
    oggmenu.Label5.Caption = iniladen(154) + ":"
    oggmenu.normalengine.Caption = iniladen(155) + ":"
    oggmenu.managementengine.Caption = iniladen(156) + ":"
    manpl.Listel.Caption = iniladen(157)
    manpl.dl.Caption = iniladen(158)
    Database.addsubs.Caption = iniladen(159)
    Database.Label1(1).Caption = iniladen(160)
    Database.Label1(2).Caption = iniladen(161)
    Database.Label1(3).Caption = iniladen(162)
    Database.Label1(4).Caption = iniladen(163)
    Statistik.Label4(1).Caption = iniladen(164) + ":"
    Statistik.Label4(2).Caption = iniladen(165) + ":"
    Statistik.Label4(0).Caption = iniladen(166) + ":"
    Statistik.Label4(3).Caption = iniladen(167) + ":"
    Statistik.Label2(0).Caption = iniladen(168) + ":"
    Statistik.Label2(1).Caption = iniladen(169) + ":"
    Statistik.Label2(2).Caption = iniladen(170) + ":"
    Statistik.Label4(4).Caption = iniladen(171) + ":"
    Statistik.Label4(6).Caption = iniladen(172) + ":"
    Statistik.Label4(5).Caption = iniladen(173) + ":"
    Statistik.Aktualisieren.Caption = iniladen(174)
    Statistik.Excelanzeigen.Caption = iniladen(175)
    DBdurchsuchen.Label3(6).Caption = iniladen(176) + ":"
    DBdurchsuchen.Label3(4).Caption = iniladen(177) + ":"
    DBdurchsuchen.Label3(8).Caption = iniladen(178) + ":"
    DBdurchsuchen.Label3(9).Caption = iniladen(179) + ":"
    DBdurchsuchen.Label3(10).Caption = iniladen(180) + ":"
    DBdurchsuchen.Label3(12).Caption = iniladen(181) + ":"
    DBdurchsuchen.Label3(14).Caption = iniladen(182) + ":"
    DBdurchsuchen.Label3(13).Caption = iniladen(183) + ":"
    DBdurchsuchen.Label3(16).Caption = iniladen(184) + ":"
    DBdurchsuchen.Label3(17).Caption = iniladen(185) + ":"
    DBdurchsuchen.Label3(15).Caption = iniladen(186) + ":"
    DBdurchsuchen.Label3(7).Caption = iniladen(187) + ":"
    DBdurchsuchen.Label3(19).Caption = iniladen(188) + ":"
    DBdurchsuchen.Label3(20).Caption = iniladen(189) + ":"
    DBdurchsuchen.Label3(21).Caption = iniladen(190) + ":"
    DBdurchsuchen.Label3(22).Caption = iniladen(191) + ":"
    DBdurchsuchen.Label3(18).Caption = iniladen(192) + ":"
    DBdurchsuchen.dbfirst.Caption = iniladen(193)
    DBdurchsuchen.suchefirst.Caption = DBdurchsuchen.dbfirst.Caption
    DBdurchsuchen.dbback.Caption = iniladen(194)
    DBdurchsuchen.sucheback.Caption = DBdurchsuchen.dbback.Caption
    DBdurchsuchen.dbnext.Caption = iniladen(195)
    DBdurchsuchen.suchenext.Caption = DBdurchsuchen.dbnext.Caption
    DBdurchsuchen.dblast.Caption = iniladen(196)
    DBdurchsuchen.suchelast.Caption = DBdurchsuchen.dblast.Caption
    DBdurchsuchen.dbkill.Caption = iniladen(197)
    DBdurchsuchen.dbnew.Caption = iniladen(198)
    DBdurchsuchen.dbsave.Caption = iniladen(199)
    Database.Caption = iniladen(200)
    DBdurchsuchen.Caption = iniladen(201)
    manpl.Caption = iniladen(202)
    MP2cbrmenu.Caption = iniladen(203)
    MP2vbrmenu.Caption = iniladen(204)
    OnAir.Caption = iniladen(205)
    oggmenu.Caption = iniladen(206)
    Pfadsuchen.Caption = iniladen(207)
    PL_Verwendung.Caption = iniladen(208)
    PlaylistLoggerSettings.Caption = iniladen(209)
    Statistik.Caption = iniladen(210)
    allgemeine.spshow.Caption = iniladen(211)
    frmMain.Label2(0).Caption = iniladen(212) + ":"
    frmMain.help.Caption = iniladen(213)
    allgemeine.igext.Caption = iniladen(214)
    Scannen.labelminfiles.Caption = iniladen(215) + ":"
End Sub
Private Function iniladen(Menu2 As String) As String
    Dim buffer As String, wertlen As Integer
    
    buffer = Space$(255)
    wertlen = GetPrivateProfileString(allgemeine.sprache.Text, Menu2, vbNullString, buffer, Len(buffer), App.Path + "\Sprache\" + allgemeine.sprache.Text + ".ini")
    iniladen = Mid$(buffer, 1, wertlen)
End Function

